### ISSUE TITLE
frida.core.RPCException: Error: missing argument

### ISSUE THREAD

**Issue by j1anFen** [hluwa/FRIDA-DEXDump#4]
请问大佬这个报错是什么原因

frida-server_12.0.5
`
root@ubuntu:~/apktool/FRIDA-DEXDump# python3 main.py
[DEXDump]: found target [24720] com.xxx.android.xxxx
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    matches = script.exports.scandex()
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: missing argument
    at frida/runtime/core.js:223
    at scandex (script1.js:13)
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)
`

**Comment by hluwa** [comment]
升级server.

**Comment by j1anFen** [comment]
好的，谢谢。
