### ISSUE TITLE
Doesn't dump correctly payload DEX

### ISSUE THREAD

**Issue by cryptax** [hluwa/frida-dexdump#46]
FRIDA-Dexdump tool does not unpack successfully the following malware and dumps an **erroneous DEX** file that disassemblers fail to process. It seems there is a **checksum** issue.

**How to reproduce / grab the sample**
See this tweet: https://twitter.com/ReBensk/status/1485569424874938371?s=20 and download `53108_Video_Oynatıcı.apk` (sha256: `62a313bcf8611205a25850405fdf45c5c207d4755411d1ce26607eeb41581fd7`). It is a **malware**, be cautious, don't install it on a real phone, rather an emulator.

**Dump the DEXes**

Launch it the app, and try to dump its DEXes with `frida-dexdump` (I personally needed to attach to its PID, the other ways did not work). You should get 2 DEXs: the main one, and the payload.

```
com.donkey.fragile$ ls
0x7acff17e401c.dex  0x7acff1a4401c.dex
```

Now, try and decompile `0x7acff17e401c.dex` (sha256: `7b9961dbba9b6fb9522d15ef7169af26e30810989b4bb8b58b40f087896d1956`). 

**Disassembly errors**

For instance, head to `com.about.across.bot.a.a`.  
With JADX, you get an error at opening the DEX: "Load failed, Error count: 1" and the following logs:

```
ERROR - File open error: /workshop/./0x7acff17e401c.dex
jadx.plugins.input.dex.DexException: Bad checksum: 0x73eb147b, expected: 0x6f8eb545
	at jadx.plugins.input.dex.utils.DexCheckSum.verify(DexCheckSum.java:22)
	at jadx.plugins.input.dex.DexFileLoader.checkFileMagic(DexFileLoader.java:57)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:40)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:35)
	at jadx.plugins.input.dex.DexInputPlugin.loadDexFiles(DexInputPlugin.java:29)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:25)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:126)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:111)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:45)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  - Loaded classes: 0, methods: 0, instructions: 0
```

With JEB decompiler you get:

```java
public static void a(Context arg5) {
        // ERROR - The method was not decompiled
        // Cannot decompile method containing odex instructions: Lcom/about/across/bot/a/a;->a(Landroid/content/Context;)V
        // Restore the original dex first, then load it into JEB.
        // Reference: https://www.pnfsoftware.com/jeb/manual/android/#optimized-dex-odex
    }
 ```

With **baksmali** you get:

```
   aput-object v3, v2, v4

    invoke-static {v0, v2}, Lcom/about/across/bot/e/d;->a(Ljava/lang/String;[Ljava/lang/Object;)V

    invoke-static {p0, v1}, Lcom/about/across/bot/a/a;->a(Landroid/content/Context;Z)V

    #disallowed odex opcode
    #return-void-no-barrier
    nop
.end method
```

With **baksmali + jd-gui**, you get:

```java
public class a {
  public static void a(Context paramContext) {
    d.a("!!!!!", new Object[] { "attempt to enable internet" });
    a(paramContext, true);
    throw new VerifyError("bad dex opcode");
  }
```
I am using latest FRIDA-Dexdump from git and Frida server **15.1.14**.

**Comment by hluwa** [comment]
Hi, when using the emulator, dump ODEX instruction often appears. Usually, these instructions cannot be restored from the dumped DEX after optimization, so I suggest using a real test phone for dump. I tested that this sample can dump the payload in the OnePlus6t/LineageOS/Android11/Frida15.1.17/frida-dexdump2.0.1/. You can see it on [VirusTotal](https://www.virustotal.com/gui/file/91d9fc8f71c0f208a7085dab52d18e7438c46d63dce7d36bf052b7f7dfc2c630?nocache=1)
