### ISSUE TITLE
frida.InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by andrewpedia** [hluwa/frida-dexdump#59]
frida.InvalidOperationError: script has been destroyed

**Comment by wgqzlj** [comment]
Same question...

**Comment by mcoo** [comment]
```
ERROR:frida-dexdump:[-] script has been destroyed: {'addr': '0xef4ae180', 'size': 7389808}
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\frida_dexdump\__main__.py", line 81, in dump
    bs = self.agent.memory_dump(dex['addr'], dex['size'])
  File "C:\Python310\lib\site-packages\frida_dexdump\agent\__init__.py", line 24, in memory_dump
    return self._rpc.memorydump(base, size)
  File "C:\Python310\lib\site-packages\frida\core.py", line 476, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "C:\Python310\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Python310\lib\site-packages\frida\core.py", line 408, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed
```

**Comment by leftshine** [comment]
Same question...

**Comment by zimya** [comment]
Same question...

**Comment by wying111** [comment]
Same question...

**Comment by chenjiaming2qiqi** [comment]
INFO:Agent:DexDumpAgent<Connection(pid=Session(pid=10185), connected:True), attached=True>: Attach.
INFO:frida-dexdump:Waiting 10s...
INFO:frida-dexdump:[+] Searching...
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\user\.conda\envs\python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida_tools\application.py", line 836, in _run
    work()
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida_tools\application.py", line 432, in _try_start
    self._start()
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida_dexdump\__main__.py", line 68, in _start
    self.dump()
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida_dexdump\__main__.py", line 74, in dump
    ranges = self.agent.search_dex(enable_deep_search=self.enable_deep)
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida_dexdump\agent\__init__.py", line 21, in search_dex
    return self._rpc.searchdex(enable_deep_search)
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida\core.py", line 476, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\user\.conda\envs\python310\lib\site-packages\frida\core.py", line 408, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed

**Comment by icukeup** [comment]
same question

**Comment by AugustineFulgur** [comment]
same

**Comment by s0ing** [comment]
same question
